name: Docker
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          docker build -t sysmana/sparkui:latest docker/sparkui
